- type: department
  parent: CMDepartmentBase
  id: CMArmy
  name: US Army
  description: cm-department-US-Army
  color: "#5D6532"
  roles:
  - RNMCArmyPlatoonOfficer
  - RNMCArmySquadLeader
  - RNMCArmyFireteamLead
  - RNMCArmyHeavyGunner
  - RNMCArmyGunner
  - RNMCArmyMedicalTechnician
  - RNMCArmyTrooper
  - RNMCAntiTankGunner
  - RNMCArmyDesignatedMarksman
  - RNMCArmyCombatTechnician
  departmentRadio: USArmy
  headOfDepartment: RNMCArmyPlatoonOfficer