- type: entity
  id: SquadSunRiders
  name: Sun Riders
  components:
  - type: SquadTeam
    color: "#4148C8"
    background:
      sprite: _RMC14/Interface/job_icons/UNMC/marine.rsi
      state: hudsquad
    radio: SunRiders
    blacklistedSquadArmor:
    - Helmet
    - Goggles
    - Armor
    - Gloves
    group: SunRiders
    minimapBackground:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: background_delta
  - type: Tag
    tags:
    - RMCSquadSunRiders

- type: entity
  id: SquadRedDawn
  name: Red Dawn
  components:
  - type: SquadTeam
    color: "#DE3A3A"
    radio: RedDawn
    blacklistedSquadArmor:
    - Helmet
    - Goggles
    - Armor
    - Gloves
    maxRoles:
      CMSPPSquadSergeantPVE: 2
      CMSPPMachinegunnerPVE: 2
      CMSPPSanitarPVE: 1
      CMSPPInfantrymanPVE: 4
      CMSPPPlatoonSergeantPVE: 1
      CMSPPPlatoonCommanderPVE: 1
    group: RedDawn
  - type: Tag
    tags:
    - RNMCSquadRedDawn

- type: entity
  id: SquadPMCOmega
  name: AZURE 15
  components:
  - type: SquadTeam
    accessLevels:
    - RNMCAccessPMCSquadOmega
    color: "#ccffe9"
    background:
      sprite: _RMC14/Interface/job_icons/UNMC/marine.rsi
      state: hudsquad
    radio: RedDawn
    blacklistedSquadArmor:
    - Helmet
    - Goggles
    - Armor
    - Gloves
    maxRoles:
      RNMCTacticalUnitPVE: 2
      RNMCPMCHeavyWeaponsSpecialistPVE: 1
      RNMCMedicalSpecialistAzurePVE: 1
      RNMCTeamLeadPVE: 1
    group: PMC
  - type: Tag
    tags:
    - RNMCSquadAzure15

- type: entity
  id: SquadPMCTheta
  name: AZURE 15
  components:
  - type: SquadTeam
    accessLevels:
    - RNMCAccessPMCSquadTheta
    color: "#ccffe9"
    background:
      sprite: _RMC14/Interface/job_icons/UNMC/marine.rsi
      state: hudsquad
    radio: WEYA
    blacklistedSquadArmor:
    - Helmet
    - Goggles
    - Armor
    - Gloves
    maxRoles:
      RNMCTacticalUnitPVE: 2
      RNMCPMCHeavyWeaponsSpecialistPVE: 1
      RNMCOperationsLeaderPVE: 1
      RNMCTeamLeadPVE: 1
    group: PMC
  - type: Tag
    tags:
    - RNMCSquadAzure15
