- type: entity
  id: SquadSunRiders
  name: Sun Riders
  components:
  - type: SquadTeam
    color: "#4148C8"
    background:
      sprite: _RMC14/Interface/cm_job_icons.rsi
      state: hudsquad
    radio: SunRiders
    blacklistedSquadArmor:
    - Helmet
    - Goggles
    - Armor
    - Gloves
    group: SunRiders
    minimapBackground:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: background_delta
  - type: Tag
    tags:
    - RMCSquadSunRiders

- type: entity
  id: SquadRedDawn
  name: Red Dawn
  components:
  - type: SquadTeam
    color: "#DE3A3A"
    background:
      sprite: _RMC14/Interface/cm_job_icons.rsi
      state: hudsquad
    radio: RedDawn
    blacklistedSquadArmor:
    - Helmet
    - Goggles
    - Armor
    - Gloves
    maxRoles:
      CMSPPSquadSergeantPVE: 2
      CMSPPMachinegunnerPVE: 2
      CMSPPSanitarPVE: 1
      CMSPPInfantrymanPVE: 4
      CMSPPPlatoonSergeantPVE: 1
      CMSPPPlatoonCommanderPVE: 1
    group: RedDawn
  - type: Tag
    tags:
    - RNMCSquadRedDawn

- type: entity
  id: SquadArmy
  name: Army
  components:
  - type: SquadTeam
    color: "#5D6532"
    background:
      sprite: _RMC14/Interface/cm_job_icons.rsi
      state: hudsquad
    radio: US Army
    blacklistedSquadArmor:
    - Helmet
    - Goggles
    - Armor
    - Gloves
    maxRoles:
      RNMCArmyPlatoonOfficer: 1
      RNMCArmySquadLeader: 1
      RNMCArmyFireteamLead: 1
      RNMCArmyGunner: 1
      RNMCArmyMedicalTechnician: 1
      RNMCArmyTrooper: 4
      RNMCAntiTankGunner: 1
      RNMCArmyDesignatedMarksman: 1
      RNMCArmyCombatTechnician: 1
    group: Army
  - type: Tag
    tags:
    - RNMCSquadArmy
    