using Content.Client._RNMC14.Narrate;
using Content.Client.Administration.Managers;
using Content.Client.UserInterface.Systems.DecalPlacer;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.Upload.Commands;
using Robust.Client.UserInterface;

namespace Content.Client._RNMC14.RNMCTab
{
    [GenerateTypedNameReferences]
    public sealed partial class RNMCTab : Control
    {
    }
}
