using Content.Shared._RNMC14.AdminNarrate;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Content.Client.Eui;
using Robust.Shared.Utility;

namespace Content.Client._RNMC14.Narrate;

[GenerateTypedNameReferences]
public sealed partial class AdminNarrateWindow : DefaultWindow
{
    [Dependency] private readonly ILocalizationManager _localization = default!;
    [Dependency] private readonly EuiManager _euiManager = default!;

    public AdminNarrateWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Narrate.Placeholder = new Rope.Leaf(_localization.GetString("admin-announce-announcement-placeholder"));
        NarrateMethod.AddItem(_localization.GetString("rnmc-narrate-type-ghosts"));
        NarrateMethod.SetItemMetadata(0, AdminNarrateType.All);
        NarrateMethod.AddItem(_localization.GetString("rnmc-narrate-type-all"));
        NarrateMethod.SetItemMetadata(1, AdminNarrateType.Ghosts);
        NarrateMethod.OnItemSelected += AnnounceMethodOnOnItemSelected;
        Narrate.OnKeyBindUp += AnnouncementOnOnTextChanged;
    }

    private void AnnouncementOnOnTextChanged(GUIBoundKeyEventArgs args)
    {
        NarrateButton.Disabled = Rope.Collapse(Narrate.TextRope).TrimStart() == "";
    }

    private void AnnounceMethodOnOnItemSelected(OptionButton.ItemSelectedEventArgs args)
    {
        NarrateMethod.SelectId(args.Id);
    }
}
