using Content.Shared._RNMC14.AdminNarrate;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Content.Client.Eui;
using Robust.Shared.Utility;

namespace Content.Client._RNMC14.Toggles;

[GenerateTypedNameReferences]
public sealed partial class AdminTogglesWindow : DefaultWindow
{   
}
