- type: job
  parent: CMJobBase
  id: CMSSPSquadSergeantPVE
  name: cm-job-name-squad-sergeant
  description: cm-job-description-squad-leader
  playTimeTracker: CMJobSPPSquadSergeantPVE
  ranks:
    RMCRankSergeant: []
  startingGear: CMGearSquadSergeantSPP
  dummyStartingGear: CMGearSquadLeaderEquipped
  icon: "RMCJobIconSPPSquadSergeant"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-section-sergeant
  accessGroups:
  - CMSSPSquadSergeantAccess
  overwatchSortPriority: -6
  overwatchShowName: true
  overwatchRoleName: Squad Sergeant
  roleWeight: 1
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - SPP
    - type: DemoSpecWhitelist
    - type: GrenadeSpecWhitelist
    - type: ScoutWhitelist
    - type: SniperWhitelist
    - type: PyroWhitelist
    - type: Skills
      skills:
        RMCSkillConstruction: 2
        RMCSkillEndurance: 2
        RMCSkillEngineer: 2
        RMCSkillFirearms: 1
        RMCSkillFireman: 3
        RMCSkillJtac: 2
        RMCSkillLeadership: 1
        RMCSkillMedical: 1
        RMCSkillVehicles: 1
        RMCSkillSpecialistWeapons: 7
        RMCSkillPowerLoader: 1
        RmcSkillPilot: 1
    - type: MarineOrders
    - type: SquadArmorWearer
      leader: true
    - type: RMCPointing
    - type: JobPrefix
      prefix: cm-job-prefix-squad-leader
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: tl

- type: playTimeTracker
  id: CMJobSSPSquadSergeantPVE
  isHumanoid: true

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointSquadSergeantRedDawn
  name: red dawn squad sergeant spawn point
  components:
  - type: SpawnPoint
    job_id: CMSPPSquadSergeantPVE
  - type: Sprite
    state: marine_spawn

- type: jobIcon
  parent: CMJobIconBase
  id: RMCJobIconSPPSquadSergeant
  icon:
    sprite: _RMC14/Interface/cm_job_icons.rsi
    state: upp_sl

- type: startingGear
  id: CMGearSquadSergeantSPP
  equipment:
    id: CMDogtagSquadSergeant

- type: entity
  parent: CMIDCardStandardDogtag
  id: CMDogtagMachinegunner
  name: Machinegunner's dogtags
  components:
  - type: PresetIdCard
    job: CMSPPSanitarPVE
