- type: job
  parent: CMJobBase
  id: CMSSPPlatoonCommanderPVE
  name: cm-job-name-platoon-commander
  description: cm-job-description-platoon-commander
  playTimeTracker: CMJobSSPPlatoonCommanderPVE
  ranks:
    RMCRankSPPStarshiyLeytenant:
    - !type:RoleTimeRequirement
      role: CMJobSSPPlatoonCommanderPVE
      time: 36000 # 10 hours
    RMCRankSPPMladshiyLeytenant: []
  weight: 5
  startingGear: CMGearPlatoonCommanderSPP
  icon: "RMCJobIconSPPPlatco"
  requireAdminNotify: true
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-co
  accessGroups:
  - CMSPPShipmasterAccess
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - SPP
    - type: DemoSpecWhitelist
    - type: GrenadeSpecWhitelist
    - type: ScoutWhitelist
    - type: SniperWhitelist
    - type: PyroWhitelist
    - type: Skills
      skills:
        RMCSkillPilot: 2
        RMCSkillNavigations: 1
        RMCSkillEndurance: 2
        RMCSkillConstruction: 2
        RMCSkillEngineer: 2
        RMCSkillFirearms: 1
        RMCSkillFireman: 3
        RMCSkillIntel: 1
        RMCSkillJtac: 3
        RMCSkillLeadership: 2
        RMCSkillMedical: 2
        RMCSkillOverwatch: 1
        RMCSkillPolice: 1
        RMCSkillPowerLoader: 1
        RMCSkillSurgery: 1
        RMCSkillVehicles: 2
        RMCSkillSpecialistWeapons: 7
    - type: MarineOrders
    - type: RMCPointing
    - type: JobPrefix
      prefix: cm-job-prefix-platoon-commander
    - type: ViewIntelObjectives
    - type: CommandAccent
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: platco

- type: playTimeTracker
  id: CMJobSSPPlatoonCommanderPVE
  isHumanoid: true

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointPlatcoRedDawn
  name: red dawn platoon commander spawn point
  components:
  - type: SpawnPoint
    job_id: CMSSPPlatoonCommanderPVE
  - type: Sprite
    state: marine_spawn

- type: jobIcon
  parent: CMJobIconBase
  id: RMCJobIconSPPPlatco
  icon:
    sprite: _RMC14/Interface/cm_job_icons.rsi
    state: upp_slt

- type: startingGear
  id: CMGearPlatoonCommanderSPP
  equipment:
    id: CMDogtagPlatoonCommander

- type: entity
  parent: CMIDCardStandardDogtag
  id: CMDogtagMachinegunner
  name: Platoon Commander's dogtags
  components:
  - type: PresetIdCard
    job: CMSPPPlatoonCommanderPVE
